export const PLUGIN_STYLES = String.raw`
[role="dialog"]:has(.dsl-root){width:min(1500px,calc(100vw - 48px));height:min(900px,calc(100vh - 48px));max-width:none}
[role="dialog"]:has(.dsl-root)>*:last-child{min-width:0;flex:1}
.dsl-root{
  --dsl-text:var(--dsw-alias-label-primary,#181818);
  --dsl-muted:var(--dsw-alias-label-secondary,#707070);
  --dsl-bg:var(--dsw-alias-bg-layer-1,#f6f6f6);
  --dsl-surface:var(--dsw-alias-bg-layer-2,#fff);
  --dsl-line:var(--dsw-alias-border-l2,#dedede);
  --dsl-line-soft:var(--dsw-alias-border-l1,#ececec);
  --dsl-primary:var(--dsw-alias-button-primary-fill,#181818);
  /* 背景层令前景色随皮肤翻转，兼容尚未提供 primary-foreground 的旧 Harness。 */
  --dsl-primary-text:var(--dsw-alias-bg-layer-1,#fff);
  --dsl-success:var(--dsw-alias-state-success-primary,#208454);
  --dsl-error:var(--dsw-alias-state-error-primary,#b6463d);
  --dsl-warning:#a26a18;
  /* 由宿主管理高度和滚动；断点跟随插件内容区，而非整个浏览器窗口。 */
  width:100%;min-width:0;min-height:100%;box-sizing:border-box;color:var(--dsl-text);font-family:inherit;
  container:dsl-workspace / inline-size;
}
.dsl-root *{box-sizing:border-box}.dsl-root button,.dsl-root input,.dsl-root select,.dsl-root textarea{font:inherit;color:inherit}.dsl-root code,.dsl-code{font-family:ui-monospace,SFMono-Regular,Consolas,"Liberation Mono",monospace}
.dsl-shell{width:100%;min-width:0;min-height:100%;display:grid;align-content:start;gap:17px;padding:4px 4px 24px}.dsl-tabs{max-width:100%;width:fit-content;display:flex;gap:5px;padding:4px;border-radius:10px;background:var(--dsl-bg)}
.dsl-tabs button{display:inline-flex;align-items:center;gap:7px;min-height:34px;padding:7px 13px;border:0;border-radius:7px;background:transparent;color:var(--dsl-muted);cursor:pointer;font-size:13px;white-space:nowrap}
.dsl-tabs button[aria-selected="true"]{background:var(--dsl-surface);color:var(--dsl-text);box-shadow:0 1px 4px rgba(0,0,0,.11);font-weight:650}
.dsl-page{width:100%;max-width:none;margin:0;display:grid;align-content:start;gap:17px;min-width:0}.dsl-page-header{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;min-width:0}
.dsl-page-header>div:first-child{min-width:0}.dsl-eyebrow{margin-bottom:5px;color:var(--dsl-muted);font-size:10px;font-weight:650;letter-spacing:.04em}.dsl-page-header h1{margin:0;font-size:23px;line-height:1.2;letter-spacing:-.02em}.dsl-page-header p{max-width:800px;margin:7px 0 0;color:var(--dsl-muted);font-size:13px;line-height:1.55}.dsl-actions,.dsl-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.dsl-button{min-height:36px;display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:7px 11px;border:1px solid var(--dsl-line);border-radius:7px;background:var(--dsl-surface);color:var(--dsl-text);cursor:pointer;font-size:13px;font-weight:520;white-space:nowrap}.dsl-button:hover:not(:disabled){background:var(--dsl-bg);border-color:var(--dsl-muted)}.dsl-button:focus-visible,.dsl-input:focus-visible,.dsl-select:focus-visible,.dsl-textarea:focus-visible{outline:2px solid color-mix(in srgb,var(--dsl-primary) 45%,transparent);outline-offset:2px}.dsl-button:disabled{opacity:.45;cursor:not-allowed}.dsl-button-primary{background:var(--dsl-primary);border-color:var(--dsl-primary);color:var(--dsl-primary-text)}.dsl-button-primary:hover:not(:disabled){background:color-mix(in srgb,var(--dsl-primary) 84%,var(--dsl-surface));border-color:var(--dsl-primary)}.dsl-button-danger{border-color:color-mix(in srgb,var(--dsl-error) 36%,var(--dsl-line));background:color-mix(in srgb,var(--dsl-error) 7%,var(--dsl-surface));color:var(--dsl-error)}.dsl-icon-button{width:34px;padding:0}.dsl-icon-button span{display:none}
.dsl-button-primary>span,.dsl-button-primary>svg{color:#fff!important;mix-blend-mode:difference}
.dsl-card,.dsl-section{min-width:0;border:1px solid var(--dsl-line);border-radius:11px;background:var(--dsl-surface)}.dsl-section{padding:16px}.dsl-status{width:fit-content;display:inline-flex;align-items:center;gap:5px;padding:4px 8px;border-radius:999px;font-size:10px;font-weight:650;white-space:nowrap}.dsl-status-success{color:var(--dsl-success);background:color-mix(in srgb,var(--dsl-success) 11%,var(--dsl-surface))}.dsl-status-warning{color:var(--dsl-warning);background:color-mix(in srgb,var(--dsl-warning) 12%,var(--dsl-surface))}.dsl-status-neutral{color:var(--dsl-muted);background:var(--dsl-bg)}
.dsl-message{display:flex;align-items:flex-start;gap:8px;padding:10px 12px;border:1px solid var(--dsl-line);border-radius:8px;font-size:12px;line-height:1.5}.dsl-message-ok{border-color:color-mix(in srgb,var(--dsl-success) 32%,var(--dsl-line));background:color-mix(in srgb,var(--dsl-success) 7%,var(--dsl-surface));color:var(--dsl-success)}.dsl-message-error{border-color:color-mix(in srgb,var(--dsl-error) 32%,var(--dsl-line));background:color-mix(in srgb,var(--dsl-error) 7%,var(--dsl-surface));color:var(--dsl-error)}
.dsl-connection-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.dsl-connection-card{padding:17px;box-shadow:0 4px 15px rgba(0,0,0,.025)}.dsl-connection-card:first-child{border-left:3px solid var(--dsl-primary)}.dsl-connection-head{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:11px;align-items:start}.dsl-db-icon,.dsl-dataset-icon,.dsl-summary-icon,.dsl-callout-icon,.dsl-topology-icon{display:grid;place-items:center;flex:none;border-radius:9px;background:var(--dsl-bg);color:var(--dsl-muted)}.dsl-db-icon{width:38px;height:38px}.dsl-db-icon.mysql{background:color-mix(in srgb,#5b83b8 15%,var(--dsl-surface));color:#5577a5}.dsl-db-icon.clickhouse{background:color-mix(in srgb,#c99421 16%,var(--dsl-surface));color:#a57412}.dsl-connection-head strong{display:block;font-size:14px}.dsl-connection-head p{margin:4px 0 0;color:var(--dsl-muted);font-size:11px;word-break:break-word}.dsl-connection-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;padding:14px 0;margin:14px 0;border-top:1px solid var(--dsl-line-soft);border-bottom:1px solid var(--dsl-line-soft)}.dsl-connection-meta small,.dsl-source-strip small{display:block;color:var(--dsl-muted);font-size:10px}.dsl-connection-meta strong{display:block;margin-top:4px;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.dsl-query-head,.dsl-section-title{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.dsl-query-head h2,.dsl-section-title h2{margin:0;font-size:14px}.dsl-query-head p,.dsl-section-title p{margin:4px 0 0;color:var(--dsl-muted);font-size:11px;line-height:1.5}.dsl-query-line{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:stretch;margin-top:12px}.dsl-query-line textarea{min-height:58px;resize:vertical}.dsl-safety{display:flex;align-items:center;gap:6px;margin-top:9px;color:var(--dsl-muted);font-size:10px}.dsl-query-result{margin-top:12px;overflow:auto;border:1px solid var(--dsl-line);border-radius:8px}.dsl-query-result table{width:100%;border-collapse:collapse;font-size:11px}.dsl-query-result th,.dsl-query-result td{padding:8px;border-bottom:1px solid var(--dsl-line-soft);text-align:left;white-space:nowrap}.dsl-query-result th{background:var(--dsl-bg)}
.dsl-input,.dsl-select,.dsl-textarea{width:100%;min-height:36px;padding:8px 10px;border:1px solid var(--dsl-line);border-radius:8px;background:var(--dsl-surface);outline:0}.dsl-textarea{min-height:68px;resize:vertical;line-height:1.5}.dsl-field{display:grid;gap:6px}.dsl-field>span{color:var(--dsl-muted);font-size:11px;font-weight:600}.dsl-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.dsl-span-2{grid-column:1/-1}.dsl-privacy{display:grid;grid-template-columns:auto minmax(0,1fr);gap:10px;align-items:start;margin-top:14px;padding:12px;border:1px solid color-mix(in srgb,var(--dsl-success) 22%,var(--dsl-line));border-radius:9px;background:color-mix(in srgb,var(--dsl-success) 6%,var(--dsl-surface));color:var(--dsl-success)}.dsl-privacy strong{display:block;font-size:11px}.dsl-privacy span{display:block;margin-top:3px;color:var(--dsl-muted);font-size:10px;line-height:1.5}
.dsl-summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:11px}.dsl-summary-card{display:grid;grid-template-columns:auto minmax(0,1fr);gap:11px;padding:15px}.dsl-summary-icon{width:37px;height:37px}.dsl-summary-card small{color:var(--dsl-muted);font-size:10px}.dsl-summary-card strong{display:block;margin-top:3px;font-size:20px}.dsl-summary-card p{margin:4px 0 0;color:var(--dsl-muted);font-size:10px;line-height:1.35}.dsl-summary-success .dsl-summary-icon{background:color-mix(in srgb,var(--dsl-success) 11%,var(--dsl-surface));color:var(--dsl-success)}.dsl-summary-warning .dsl-summary-icon{background:color-mix(in srgb,var(--dsl-warning) 11%,var(--dsl-surface));color:var(--dsl-warning)}
.dsl-dataset-list{padding:0;overflow:hidden}.dsl-list-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;border-bottom:1px solid var(--dsl-line-soft)}.dsl-search{width:min(360px,100%);display:flex;align-items:center;gap:8px;padding:0 10px;border:1px solid var(--dsl-line);border-radius:8px;background:var(--dsl-surface)}.dsl-search input{width:100%;height:34px;border:0;background:transparent;outline:0}.dsl-table-scroll{overflow-x:auto}.dsl-dataset-head,.dsl-dataset-row{min-width:930px;display:grid;grid-template-columns:minmax(270px,1.6fr) minmax(160px,.9fr) minmax(120px,.65fr) 80px 104px 34px;gap:12px;align-items:center}.dsl-dataset-head{padding:9px 14px;background:var(--dsl-bg);border-bottom:1px solid var(--dsl-line-soft);color:var(--dsl-muted);font-size:10px;font-weight:650}.dsl-dataset-row{padding:14px;border-bottom:1px solid var(--dsl-line-soft);cursor:pointer}.dsl-dataset-row:last-child{border-bottom:0}.dsl-dataset-row:hover{background:var(--dsl-bg)}.dsl-dataset-main{min-width:0;display:grid;grid-template-columns:auto minmax(0,1fr);gap:10px;align-items:start}.dsl-dataset-icon{width:34px;height:34px}.dsl-dataset-main strong{font-size:13px}.dsl-dataset-main code{margin-left:8px;color:var(--dsl-muted);font-size:10px}.dsl-dataset-main p{margin:5px 0 0;color:var(--dsl-muted);font-size:10px;line-height:1.4;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.dsl-source-cell span{display:block;font-size:11px;font-weight:650}.dsl-source-cell small,.dsl-coverage small,.dsl-updated{color:var(--dsl-muted);font-size:10px}.dsl-coverage strong{font-size:11px}.dsl-progress{height:4px;margin:5px 0;background:var(--dsl-bg);border-radius:99px;overflow:hidden}.dsl-progress i{display:block;height:100%;background:var(--dsl-primary)}.dsl-relation-count{display:flex;align-items:center;gap:5px;font-size:11px}.dsl-row-action{width:30px;height:30px;display:grid;place-items:center;border:0;border-radius:7px;background:transparent;cursor:pointer}.dsl-row-action:hover{background:var(--dsl-bg)}.dsl-empty{padding:34px;color:var(--dsl-muted);text-align:center;font-size:12px}
.dsl-semantic-callout{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:13px;align-items:center;padding:14px 15px;border:1px solid var(--dsl-line);border-radius:11px;background:var(--dsl-bg)}.dsl-callout-icon{width:42px;height:42px;background:var(--dsl-surface);box-shadow:0 2px 7px rgba(0,0,0,.06)}.dsl-semantic-callout strong{font-size:13px}.dsl-semantic-callout p{margin:5px 0 0;color:var(--dsl-muted);font-size:11px;line-height:1.45}
.dsl-identity{padding:18px}.dsl-identity-grid{display:grid;grid-template-columns:minmax(220px,.8fr) minmax(320px,1.6fr);gap:14px}.dsl-source-picker{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) auto;gap:10px;align-items:end;margin-top:15px;padding-top:15px;border-top:1px solid var(--dsl-line-soft)}.dsl-source-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) auto;gap:12px;align-items:center;margin-top:15px;padding-top:15px;border-top:1px solid var(--dsl-line-soft)}.dsl-source-strip>span:not(.dsl-status){min-width:0}.dsl-source-strip strong{display:block;margin-top:4px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.dsl-detail-tabs{display:flex;gap:5px;border-bottom:1px solid var(--dsl-line)}.dsl-detail-tabs button{padding:9px 14px;border:0;border-bottom:2px solid transparent;background:transparent;color:var(--dsl-muted);cursor:pointer;font-size:12px}.dsl-detail-tabs button.active{border-bottom-color:var(--dsl-primary);color:var(--dsl-text);font-weight:650}
.dsl-field-wrap{width:100%;overflow:auto;border:1px solid var(--dsl-line);border-radius:8px}.dsl-field-table{width:100%;min-width:1200px;border-collapse:collapse;table-layout:fixed}.dsl-field-table th{padding:9px 8px;background:var(--dsl-bg);border-bottom:1px solid var(--dsl-line);color:var(--dsl-muted);font-size:10px;text-align:left}.dsl-field-table td{padding:9px 8px;border-bottom:1px solid var(--dsl-line-soft);vertical-align:top;font-size:10px}.dsl-field-table tr:last-child td{border-bottom:0}.dsl-field-table th:nth-child(1),.dsl-field-table td:nth-child(1){width:52px;text-align:center}.dsl-field-table th:nth-child(2),.dsl-field-table td:nth-child(2){width:140px}.dsl-field-table th:nth-child(3),.dsl-field-table td:nth-child(3){width:125px}.dsl-field-table th:nth-child(4),.dsl-field-table td:nth-child(4){width:150px}.dsl-field-table th:nth-child(5),.dsl-field-table td:nth-child(5){width:155px}.dsl-field-table th:nth-child(6),.dsl-field-table td:nth-child(6){width:330px}.dsl-field-table th:nth-child(7),.dsl-field-table td:nth-child(7){width:175px}.dsl-field-table th:nth-child(8),.dsl-field-table td:nth-child(8){width:62px;text-align:center}.dsl-field-table input[type="checkbox"]{width:16px;height:16px;accent-color:var(--dsl-primary)}.dsl-field-code{display:grid;gap:5px;justify-items:start}.dsl-type{display:inline-block;padding:4px 6px;border:1px solid color-mix(in srgb,#647794 25%,var(--dsl-line));border-radius:5px;background:color-mix(in srgb,#647794 8%,var(--dsl-surface));color:color-mix(in srgb,var(--dsl-text) 76%,#647794);font-size:10px;word-break:break-word}.dsl-db-comment{color:var(--dsl-muted);line-height:1.45}.dsl-fields-footer{display:flex;justify-content:space-between;gap:12px;color:var(--dsl-muted);font-size:10px}.dsl-fields-footer strong{color:var(--dsl-text)}
.dsl-topology-manager{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:0;padding:0;overflow:visible}.dsl-topology-primary{display:grid;grid-template-columns:auto minmax(0,1fr);gap:12px;align-items:start;padding:15px 16px}.dsl-topology-icon{width:42px;height:42px;background:color-mix(in srgb,#637794 14%,var(--dsl-surface));color:#647794}.dsl-topology-copy{min-width:0;display:grid;gap:4px}.dsl-topology-copy small{color:var(--dsl-muted);font-size:9px}.dsl-topology-copy select{width:min(520px,100%);padding:7px 9px;border:1px solid var(--dsl-line);border-radius:8px;background:var(--dsl-bg);font-size:14px;font-weight:700}.dsl-topology-copy p{margin:0;color:var(--dsl-muted);font-size:10px;line-height:1.45}.dsl-topology-side{display:grid;align-content:center;gap:9px;padding:14px 16px;border-left:1px solid var(--dsl-line-soft);background:var(--dsl-bg)}.dsl-topology-stats{display:flex;justify-content:flex-end;gap:8px}.dsl-topology-stats span{min-width:62px;display:grid;place-items:center;gap:2px;padding:7px 9px;border:1px solid var(--dsl-line);border-radius:8px;background:var(--dsl-surface)}.dsl-topology-stats strong{font-size:13px}.dsl-topology-stats small{color:var(--dsl-muted);font-size:8px}.dsl-topology-scope{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:12px 16px;border-top:1px solid var(--dsl-line);background:var(--dsl-bg)}.dsl-topology-scope>div:first-child{display:flex;align-items:center;gap:10px;min-width:0}.dsl-topology-scope strong{display:block;font-size:11px}.dsl-topology-scope small{display:block;color:var(--dsl-muted);font-size:9px;line-height:1.4}
.dsl-legend{display:flex;align-items:center;gap:15px;flex-wrap:wrap;color:var(--dsl-muted);font-size:10px}.dsl-legend span{display:flex;align-items:center;gap:6px}.dsl-legend i{display:block;width:23px;border-top:2px solid var(--dsl-text)}.dsl-legend i.candidate{border-top-style:dashed;color:var(--dsl-warning)}.dsl-topology-grid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(310px,.55fr);gap:12px;min-width:0}.dsl-graph{position:relative;min-height:515px;overflow:auto;padding:28px;border:1px solid var(--dsl-line);border-radius:9px;background:var(--dsl-bg)}.dsl-graph-grid{position:relative;z-index:2;min-width:620px;display:grid;grid-template-columns:repeat(2,minmax(240px,1fr));gap:85px 90px}.dsl-node{overflow:hidden;border:1px solid var(--dsl-line);border-radius:9px;background:var(--dsl-surface);box-shadow:0 4px 14px rgba(0,0,0,.05)}.dsl-node-head{display:grid;grid-template-columns:auto minmax(0,1fr);gap:8px;padding:10px 11px;border-bottom:1px solid var(--dsl-line);background:var(--dsl-bg)}.dsl-node-head strong{display:block;font-size:11px}.dsl-node-head code{display:block;margin-top:3px;color:var(--dsl-muted);font-size:8px;overflow:hidden;text-overflow:ellipsis}.dsl-node-fields{display:grid}.dsl-node-field{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:6px 10px;border-bottom:1px solid var(--dsl-line-soft);font-size:9px}.dsl-node-field:last-child{border-bottom:0}.dsl-node-field span{color:var(--dsl-muted)}.dsl-relation-ribbon{grid-column:1/-1;display:flex;align-items:center;justify-content:center;gap:8px;margin:-55px 0 -55px;color:var(--dsl-muted);font-size:9px}.dsl-relation-ribbon::before,.dsl-relation-ribbon::after{content:"";width:88px;border-top:2px solid var(--dsl-text)}.dsl-relation-ribbon.candidate::before,.dsl-relation-ribbon.candidate::after{border-top-style:dashed;border-color:var(--dsl-warning)}.dsl-inspector{display:grid;gap:10px;align-content:start}.dsl-relation-card{padding:13px}.dsl-relation-card+.dsl-relation-card{margin-top:8px}.dsl-endpoint{padding:7px 8px;border:1px solid var(--dsl-line-soft);border-radius:6px;background:var(--dsl-bg)}.dsl-endpoint code{display:block;font-size:9px;word-break:break-all}.dsl-endpoint small{display:block;margin-top:3px;color:var(--dsl-muted);font-size:8px}.dsl-arrow{display:grid;place-items:center;height:24px;color:var(--dsl-muted)}.dsl-rule-details summary{cursor:pointer;font-weight:650;font-size:11px}.dsl-rule-list{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:10px}.dsl-rule-list span{padding:8px;border:1px solid var(--dsl-line-soft);border-radius:7px;background:var(--dsl-bg);font-size:9px}
.dsl-modal-backdrop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:24px;background:rgba(15,15,15,.42);backdrop-filter:blur(3px)}.dsl-modal{width:min(760px,calc(100vw - 36px));max-height:min(820px,calc(100vh - 36px));display:grid;grid-template-rows:auto minmax(0,1fr) auto;overflow:hidden;border:1px solid var(--dsl-line);border-radius:15px;background:var(--dsl-surface);box-shadow:0 28px 80px rgba(0,0,0,.25)}.dsl-modal-wide{width:min(1040px,calc(100vw - 36px))}.dsl-modal-header{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding:20px 22px 16px;border-bottom:1px solid var(--dsl-line-soft)}.dsl-modal-header h2{margin:3px 0 0;font-size:20px}.dsl-modal-header p{margin:6px 0 0;color:var(--dsl-muted);font-size:12px;line-height:1.55}.dsl-modal-body{min-height:0;overflow:auto;padding:18px 22px}.dsl-modal-footer{display:flex;justify-content:flex-end;gap:8px;padding:13px 22px;border-top:1px solid var(--dsl-line-soft)}.dsl-modal-close{width:32px;height:32px;display:grid;place-items:center;border:1px solid var(--dsl-line-soft);border-radius:9px;background:var(--dsl-bg);cursor:pointer}.dsl-export-list,.dsl-context-switcher{display:grid;gap:8px}.dsl-export-item,.dsl-context-switcher button{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px;border:1px solid var(--dsl-line);border-radius:9px;background:var(--dsl-surface);text-align:left}.dsl-export-item.selected,.dsl-context-switcher button.selected{border-color:var(--dsl-muted);background:var(--dsl-bg)}.dsl-context-layout{display:grid;grid-template-columns:240px minmax(0,1fr);gap:14px}.dsl-context-switcher button{grid-template-columns:minmax(0,1fr);cursor:pointer}.dsl-context-switcher strong,.dsl-context-switcher code{display:block;font-size:10px}.dsl-context-switcher small{color:var(--dsl-muted);font-size:9px}.dsl-context-panel{display:grid;gap:12px}.dsl-context-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.dsl-context-block{padding:13px;border:1px solid var(--dsl-line);border-radius:9px}.dsl-context-block h3{margin:0 0 10px;font-size:12px}.dsl-context-block pre{max-height:360px;overflow:auto;margin:0;padding:11px;border-radius:7px;background:var(--dsl-bg);font-size:10px;white-space:pre-wrap}.dsl-context-field{display:grid;grid-template-columns:minmax(90px,.5fr) minmax(0,1fr);gap:8px;padding:6px 0;border-bottom:1px solid var(--dsl-line-soft);font-size:9px}.dsl-context-field:last-child{border:0}.dsl-context-field strong{display:block;font-size:10px}.dsl-context-field span{color:var(--dsl-muted)}
.dsl-concepts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:12px}.dsl-concept{padding:11px;border:1px solid var(--dsl-line);border-radius:8px}.dsl-concept p{margin:5px 0;color:var(--dsl-muted);font-size:10px;line-height:1.45}.dsl-concept small{color:var(--dsl-muted);font-size:9px}.dsl-hint{padding:13px;border:1px dashed var(--dsl-line);border-radius:8px;color:var(--dsl-muted);font-size:11px;line-height:1.5}
/* 卡片按实际可用宽度自动换列，空白区域不再受固定页面宽度限制。 */
.dsl-source-browser{margin-top:15px;padding-top:15px;border-top:1px solid var(--dsl-line-soft)}
.dsl-source-heading{display:flex;align-items:center;gap:8px;flex-wrap:wrap;font-size:11px}
.dsl-source-heading span{color:var(--dsl-muted);font-size:10px}
.dsl-source-browser .dsl-source-picker{grid-template-columns:repeat(3,minmax(0,1fr));margin-top:10px;padding-top:0;border-top:0}
.dsl-source-control{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center}
.dsl-source-feedback{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:10px;color:var(--dsl-muted);font-size:11px;line-height:1.5}
.dsl-source-feedback .dsl-message{width:100%;align-items:center;flex-wrap:wrap}.dsl-source-feedback .dsl-message>span{flex:1 1 220px;overflow-wrap:anywhere}
.dsl-select:disabled{opacity:.65;cursor:not-allowed}
.dsl-required{color:var(--dsl-error);font-size:10px;font-weight:600;white-space:nowrap}
.dsl-field-error{color:var(--dsl-error);font-size:11px;line-height:1.5;overflow-wrap:anywhere}
.dsl-field-hint,.dsl-form-note{color:var(--dsl-muted);font-size:11px;line-height:1.5}
.dsl-form-note{margin:0 0 14px}.dsl-form-note .dsl-required{margin-right:4px}
.dsl-input[aria-invalid="true"],.dsl-select[aria-invalid="true"]{border-color:var(--dsl-error)}
.dsl-validation-summary{padding:12px 15px;border:1px solid color-mix(in srgb,var(--dsl-error) 40%,var(--dsl-line));border-radius:9px;background:color-mix(in srgb,var(--dsl-error) 6%,var(--dsl-surface));color:var(--dsl-error);font-size:12px;line-height:1.6}
.dsl-validation-summary ul{margin:5px 0 0;padding-left:19px}.dsl-validation-summary button{border:0;background:transparent;color:inherit;cursor:pointer;text-align:left;padding:2px 0;white-space:normal;overflow-wrap:anywhere;text-decoration:underline;text-underline-offset:3px}
.dsl-validation-summary button:focus-visible{outline:2px solid var(--dsl-error);outline-offset:2px}
.dsl-source-browser:focus-visible,.dsl-source-strip:focus-visible{outline:2px solid var(--dsl-error);outline-offset:4px}
.dsl-preview-modes{display:flex;gap:4px;margin-bottom:16px;padding:4px;width:fit-content;background:var(--dsl-bg);border:1px solid var(--dsl-line);border-radius:9px}.dsl-preview-modes button{border:0;background:transparent;border-radius:6px;padding:8px 15px;cursor:pointer;color:var(--dsl-muted);font:inherit}.dsl-preview-modes button.selected{background:var(--dsl-surface);color:var(--dsl-text);box-shadow:0 1px 4px #0001;font-weight:600}
.dsl-preview-layout{align-items:start}.dsl-preview-layout .dsl-context-switcher{align-content:start;align-items:start;gap:8px;min-width:0}.dsl-preview-layout .dsl-context-switcher>button{min-height:0;height:auto;padding:12px;gap:6px}.dsl-preview-layout .dsl-context-switcher small{color:var(--dsl-muted)}.dsl-preview-pages{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:12px}.dsl-preview-pages .dsl-button{font-size:11px}
.dsl-preview-controls{display:flex;align-items:end;flex-wrap:wrap;gap:10px;margin-top:12px}.dsl-preview-controls .dsl-field{flex:1 1 200px}.dsl-preview-explanation{margin-top:14px;color:var(--dsl-muted)}.dsl-context-panel details>summary{cursor:pointer;font-size:11px}.dsl-context-panel details[open]>summary{margin-bottom:10px}.dsl-context-panel p,.dsl-context-panel small{line-height:1.65;overflow-wrap:anywhere}.dsl-context-panel small{color:var(--dsl-muted)}.dsl-context-panel pre{max-height:300px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}
.dsl-semantic-fields>div{display:grid;grid-template-columns:minmax(100px,.45fr) minmax(0,1fr);gap:14px;padding:10px 0;border-bottom:1px solid var(--dsl-line-soft);font-size:12px}.dsl-semantic-fields code,.dsl-semantic-fields span{min-width:0;overflow-wrap:anywhere}.dsl-semantic-fields small,.dsl-semantic-fields strong{display:block}.dsl-semantic-fields strong{margin-bottom:4px}.dsl-semantic-fields details{margin-top:6px;color:var(--dsl-muted)}.dsl-semantic-fields details p{margin:5px 0}.dsl-preview-search{max-width:250px}.dsl-preview-metrics{display:flex;gap:16px;flex-wrap:wrap}.dsl-preview-warning{color:var(--dsl-warning)}
.dsl-preview-relation{display:flex;flex-wrap:wrap;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--dsl-line-soft)}.dsl-preview-relation>span{flex:1 1 200px;min-width:0}.dsl-preview-relation>p{flex:1 1 200px;min-width:0}.dsl-preview-relation code{overflow-wrap:anywhere}.dsl-preview-relation strong,.dsl-preview-relation small{display:block}
.dsl-field-picker{padding:10px 0}.dsl-field-choices{display:grid;gap:8px;margin-top:10px}.dsl-field-choices label{display:flex;align-items:start;gap:8px;font-size:11px}.dsl-field-choices label span{min-width:0;overflow-wrap:anywhere}.dsl-field-choices small{display:block}.dsl-batch-row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:10px}.dsl-batch-row>div{min-width:0;overflow-wrap:anywhere}.dsl-batch-row p{margin:5px 0}.dsl-batch-row .dsl-button{flex-shrink:0}
.dsl-comment-copy{margin-top:12px;padding:12px;border:1px solid var(--dsl-line-soft);border-radius:8px;background:var(--dsl-bg);min-width:0}
.dsl-comment-copy-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.dsl-comment-copy-toolbar>strong{font-size:11px}
.dsl-comment-copy-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;min-width:0;max-width:100%}.dsl-comment-copy-actions .dsl-select{width:auto;max-width:100%}
.dsl-comment-copy-hint{margin:8px 0 0;color:var(--dsl-muted);font-size:11px;line-height:1.6;overflow-wrap:anywhere}
.dsl-comment-copy-result{display:grid;gap:4px;margin-top:9px;padding-top:9px;border-top:1px solid var(--dsl-line);font-size:11px;line-height:1.6;overflow-wrap:anywhere}.dsl-comment-copy-result>span{color:var(--dsl-muted)}
.dsl-comment-copy-result details{color:var(--dsl-warning)}.dsl-comment-copy-result summary{cursor:pointer}.dsl-comment-copy-result ul{margin:6px 0 0;padding-left:20px}
.dsl-connection-grid{grid-template-columns:repeat(auto-fit,minmax(min(100%,420px),1fr))}
.dsl-summary-grid{grid-template-columns:repeat(auto-fit,minmax(min(100%,240px),1fr))}
.dsl-field,.dsl-input,.dsl-select,.dsl-textarea,.dsl-search,.dsl-search input{min-width:0}
.dsl-list-toolbar{flex-wrap:wrap}.dsl-search{flex:0 1 360px;max-width:100%}
.dsl-page-header>.dsl-actions{min-width:0;max-width:100%}
.dsl-connection-head strong,.dsl-source-cell,.dsl-node-head strong{overflow-wrap:anywhere}
.dsl-query-head,.dsl-section-title,.dsl-fields-footer,.dsl-safety{flex-wrap:wrap}
@container dsl-workspace (max-width:980px){
  .dsl-page-header{align-items:flex-start;flex-direction:column}
  .dsl-page-header>.dsl-actions{width:100%}
  .dsl-topology-grid,.dsl-topology-manager{grid-template-columns:1fr}
  .dsl-topology-side{border-left:0;border-top:1px solid var(--dsl-line-soft)}
  .dsl-topology-stats{justify-content:flex-start}
  .dsl-topology-scope{grid-column:auto;align-items:flex-start;flex-direction:column}
  .dsl-rule-list{grid-template-columns:repeat(2,minmax(0,1fr))}
}
@container dsl-workspace (max-width:720px){
  .dsl-shell{padding-inline:0}.dsl-tabs{width:100%;overflow:auto}.dsl-tabs button{flex:1}
  .dsl-query-line,.dsl-identity-grid,.dsl-source-picker,.dsl-source-strip{grid-template-columns:1fr}
  .dsl-source-browser .dsl-source-picker{grid-template-columns:1fr}
  .dsl-page>.dsl-section>.dsl-form-grid{grid-template-columns:1fr}
  .dsl-list-toolbar{align-items:stretch}.dsl-list-toolbar>.dsl-actions{width:100%}
  .dsl-semantic-callout{grid-template-columns:auto minmax(0,1fr)}
  .dsl-semantic-callout .dsl-button{grid-column:1/-1}
  .dsl-graph{padding:16px}.dsl-graph-grid{min-width:520px}
  .dsl-topology-primary{grid-template-columns:1fr}.dsl-topology-icon{display:none}
}
@container dsl-workspace (max-width:420px){
  .dsl-connection-meta{grid-template-columns:1fr}
  .dsl-detail-tabs{overflow-x:auto}.dsl-detail-tabs button{flex:none}
}
@media(max-width:720px){.dsl-source-browser .dsl-source-picker{grid-template-columns:1fr}}
@media(max-width:980px){.dsl-topology-grid{grid-template-columns:1fr}.dsl-topology-manager{grid-template-columns:1fr}.dsl-topology-side{border-left:0;border-top:1px solid var(--dsl-line-soft)}.dsl-topology-stats{justify-content:flex-start}.dsl-topology-scope{grid-column:auto;align-items:flex-start;flex-direction:column}.dsl-rule-list{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:720px){.dsl-shell{padding-inline:0}.dsl-tabs{width:100%;overflow:auto}.dsl-tabs button{flex:1}.dsl-page-header{align-items:flex-start;flex-direction:column}.dsl-page-header .dsl-actions{width:100%}.dsl-connection-meta{grid-template-columns:1fr}.dsl-query-line,.dsl-form-grid,.dsl-identity-grid,.dsl-source-picker,.dsl-source-strip,.dsl-context-layout,.dsl-context-columns,.dsl-concepts{grid-template-columns:1fr}.dsl-span-2{grid-column:auto}.dsl-semantic-callout{grid-template-columns:auto minmax(0,1fr)}.dsl-semantic-callout .dsl-button{grid-column:1/-1}.dsl-modal-backdrop{padding:8px}.dsl-modal,.dsl-modal-wide{width:calc(100vw - 16px);max-height:calc(100vh - 16px)}.dsl-graph{padding:16px}.dsl-graph-grid{min-width:520px}.dsl-topology-primary{grid-template-columns:1fr}.dsl-topology-icon{display:none}}
.dsl-query-pagination{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px;margin:14px 0;min-width:0}
.dsl-query-pagination label{display:flex;align-items:center;gap:8px}.dsl-query-pagination .dsl-select{width:110px}
.dsl-query-pagination>span{flex:1 1 220px;color:var(--dsl-muted);font-size:12px;text-align:center}
.dsl-query-fragment{margin-top:12px;min-width:0}.dsl-query-fragment pre{max-height:300px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;background:var(--dsl-bg);padding:12px;border:1px solid var(--dsl-line)}
.dsl-query-notes{color:var(--dsl-muted);font-size:12px;line-height:1.6}.dsl-query-notes summary{cursor:pointer}
.dsl-paged-table{max-height:max(80px,min(43vh,390px,calc(100dvh - 480px)));overflow:auto;min-width:0}.dsl-paged-table th{position:sticky;top:0;background:var(--dsl-surface);z-index:1}
.dsl-numbered-pagination{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:10px;margin:14px 0;color:var(--dsl-muted);font-size:12px;min-width:0}
.dsl-page-buttons,.dsl-numbered-pagination form,.dsl-numbered-pagination label{display:flex;flex-wrap:wrap;align-items:center;gap:6px}.dsl-page-buttons .dsl-button{min-width:34px;padding-inline:9px}.dsl-numbered-pagination .dsl-input{width:66px;padding:7px}.dsl-numbered-pagination form{margin:0}
`;
