import { readFileSync } from 'node:fs'

// 用户 2026 原标识不透明像素：深蓝 RGB(41,45,205)，亮蓝 RGB(3,150,253)。
export const GTRONTEC_TOKENS = {
  '--dsw-alias-bg-base': '#f8faff',
  '--dsw-alias-bg-layer-1': '#ffffff',
  '--dsw-alias-bg-layer-2': '#f0f4ff',
  '--dsw-alias-bg-layer-3': '#e8eeff',
  '--dsw-alias-bg-overlay': '#ffffff',
  '--dsw-alias-bg-module-platform': '#f0f4ff',
  '--dsw-alias-bg-multi-select': '#e8edff',
  '--dsw-alias-bg-skeleton': '#e8edfa',
  '--dsw-alias-border-l1': '#e5eaf8',
  '--dsw-alias-border-l2': '#d5def3',
  '--dsw-alias-border-l2-darkmode-thin': '#d5def3',
  '--dsw-alias-border-l3': '#bcc9ec',
  '--dsw-alias-border-l4': '#8b9cce',
  '--dsw-alias-border-inverted': '#d5def3',
  '--dsw-alias-border-inverted2': '#e5eaf8',
  '--dsw-alias-brand-primary': '#292dcd',
  '--dsw-alias-brand-primary-invert': '#ffffff',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#292dcd',
  '--dsw-alias-brand-text': '#292dcd',
  '--dsw-alias-button-contrast-fill': '#17254b',
  '--dsw-alias-button-elevated-fill': '#ffffff',
  '--dsw-alias-button-floating-fill': '#ffffff',
  '--dsw-alias-button-floating-hover': '#edf1ff',
  '--dsw-alias-button-ghost-active-border': '#a6b3f4',
  '--dsw-alias-button-ghost-active-fill': '#e9edff',
  '--dsw-alias-button-ghost-active-hover': '#dfe5ff',
  '--dsw-alias-button-info-fill': '#edf1ff',
  '--dsw-alias-button-info-hover': '#e2e9ff',
  '--dsw-alias-button-primary-dimmed': '#9395e6',
  '--dsw-alias-button-primary-fill': '#292dcd',
  '--dsw-alias-button-primary-hover': '#2024a7',
  '--dsw-alias-button-tool-bar-fill': '#edf1ff',
  '--dsw-alias-button-tool-bar-fill-invisible': 'transparent',
  '--dsw-alias-button-tool-bar-hover': '#e2e9ff',
  '--dsw-alias-interactive-bg-active': '#e2e8ff',
  '--dsw-alias-interactive-bg-hover': '#edf1ff',
  '--dsw-alias-interactive-bg-hover-accent': '#e8edff',
  '--dsw-alias-interactive-bg-hover-solid': '#edf1ff',
  '--dsw-alias-label-primary': '#17254b',
  '--dsw-alias-label-primary-bluish': '#17254b',
  '--dsw-alias-label-primary-dimmed': '#526185',
  '--dsw-alias-label-primary-foreground': '#ffffff',
  '--dsw-alias-label-primary-inverted': '#ffffff',
  '--dsw-alias-label-secondary': '#526185',
  '--dsw-alias-label-tertiary': '#637094',
  '--dsw-alias-label-caption': '#637094',
  '--dsw-alias-label-dimmed': '#7884a4',
  '--dsw-alias-markdown-citation': '#292dcd',
  '--dsw-alias-markdown-code-block': '#eef2fc',
  '--dsw-alias-markdown-code-block-banner': '#e5ebfa',
  '--dsw-alias-markdown-code-segment-selected': '#dce4ff',
  '--dsw-alias-markdown-inline-code': '#eaf0ff',
  '--dsw-alias-markdown-placeholder': '#637094',
  '--dsw-alias-markdown-tag': '#e8edff',
  '--dsw-alias-scrollbar-bg-l1': 'rgba(49, 72, 145, 0.12)',
  '--dsw-alias-scrollbar-bg-l2': 'rgba(49, 72, 145, 0.18)',
  '--dsw-alias-scrollbar-hover-l1': 'rgba(49, 72, 145, 0.25)',
  '--dsw-alias-scrollbar-hover-l2': 'rgba(49, 72, 145, 0.32)',
  '--dsw-alias-state-business-primary': '#292dcd',
  '--dsw-alias-state-business-tertiary': '#e8edff',
  '--dsw-alias-toast-bg': '#ffffff',
  '--dsw-alias-tooltip-bg': '#ffffff',
  '--dsw-specific-bubble': '#edf1ff',
  '--dsw-specific-bubble-highlight': '#e2e9ff',
  '--dsw-specific-input-major': '#ffffff',
  '--dsw-specific-login-input': '#ffffff',
  '--dsw-specific-menu': '#ffffff',
  '--dsw-specific-selector': '#ffffff',
  '--dsw-specific-sidebar-fill': '#f0f4ff',
  '--dsw-specific-sidebar-nav-item-active': '#e1e7ff',
  '--dsw-specific-sidebar-nav-item-active-accent': '#292dcd',
  '--dsw-specific-sidebar-nav-item-hover': '#e7edff',
  '--dsw-specific-tip': '#edf1ff',
  '--gtrontec-accent': '#0396fd',
}

export const GTRONTEC_SKIN = Object.freeze({
  id: 'gtrontec', name: '格创东智', builtin: true, version: '1.0.0',
  author: '格创东智', description: '2026 标识深蓝与亮蓝 · 清透浅色界面 · 低对比度品牌底纹 · 能碳大脑欢迎页',
  colorScheme: 'light', tokens: GTRONTEC_TOKENS,
  css: readFileSync(new URL('../assets/gtrontec/theme.css', import.meta.url), 'utf8'),
  background: null,
})

// 仅开放明确列出的品牌资源，不根据用户路径读取磁盘。
export const GTRONTEC_ASSETS = Object.freeze({
  'logo-en.png': 'image/png',
  'logo-zh.png': 'image/png',
  'favicon.svg': 'image/svg+xml',
})
