import { readFileSync } from 'node:fs'

// 原始蓝色英文 PNG 的不透明像素主色：RGB(14, 26, 223)。
export const OCTACARBON_TOKENS = {
  '--dsw-alias-bg-base': '#f8faff',
  '--dsw-alias-bg-layer-1': '#ffffff',
  '--dsw-alias-bg-layer-2': '#f0f4ff',
  '--dsw-alias-bg-layer-3': '#e8eeff',
  '--dsw-alias-bg-overlay': '#ffffff',
  '--dsw-alias-bg-module-platform': '#f0f4ff',
  '--dsw-alias-bg-multi-select': '#e8edff',
  '--dsw-alias-bg-skeleton': '#e8edfa',
  '--dsw-alias-border-l1': '#e5eaf8',
  '--dsw-alias-border-l2': '#d5def3',
  '--dsw-alias-border-l2-darkmode-thin': '#d5def3',
  '--dsw-alias-border-l3': '#bcc9ec',
  '--dsw-alias-border-l4': '#8b9cce',
  '--dsw-alias-border-inverted': '#d5def3',
  '--dsw-alias-border-inverted2': '#e5eaf8',
  '--dsw-alias-brand-primary': '#0e1adf',
  '--dsw-alias-brand-primary-invert': '#ffffff',
  '--dsw-alias-brand-primary-new-colorprimary-new-color': '#0e1adf',
  '--dsw-alias-brand-text': '#0e1adf',
  '--dsw-alias-button-contrast-fill': '#17254b',
  '--dsw-alias-button-elevated-fill': '#ffffff',
  '--dsw-alias-button-floating-fill': '#ffffff',
  '--dsw-alias-button-floating-hover': '#edf1ff',
  '--dsw-alias-button-ghost-active-border': '#a6b3f4',
  '--dsw-alias-button-ghost-active-fill': '#e9edff',
  '--dsw-alias-button-ghost-active-hover': '#dfe5ff',
  '--dsw-alias-button-info-fill': '#edf1ff',
  '--dsw-alias-button-info-hover': '#e2e9ff',
  '--dsw-alias-button-primary-dimmed': '#8e96ee',
  '--dsw-alias-button-primary-fill': '#0e1adf',
  '--dsw-alias-button-primary-hover': '#0912b8',
  '--dsw-alias-button-tool-bar-fill': '#edf1ff',
  '--dsw-alias-button-tool-bar-fill-invisible': 'transparent',
  '--dsw-alias-button-tool-bar-hover': '#e2e9ff',
  '--dsw-alias-interactive-bg-active': '#e2e8ff',
  '--dsw-alias-interactive-bg-hover': '#edf1ff',
  '--dsw-alias-interactive-bg-hover-accent': '#e8edff',
  '--dsw-alias-interactive-bg-hover-solid': '#edf1ff',
  '--dsw-alias-label-primary': '#17254b',
  '--dsw-alias-label-primary-bluish': '#17254b',
  '--dsw-alias-label-primary-dimmed': '#526185',
  '--dsw-alias-label-primary-foreground': '#ffffff',
  '--dsw-alias-label-primary-inverted': '#ffffff',
  '--dsw-alias-label-secondary': '#526185',
  '--dsw-alias-label-tertiary': '#637094',
  '--dsw-alias-label-caption': '#637094',
  '--dsw-alias-label-dimmed': '#7884a4',
  '--dsw-alias-markdown-citation': '#0e1adf',
  '--dsw-alias-markdown-code-block': '#eef2fc',
  '--dsw-alias-markdown-code-block-banner': '#e5ebfa',
  '--dsw-alias-markdown-code-segment-selected': '#dce4ff',
  '--dsw-alias-markdown-inline-code': '#eaf0ff',
  '--dsw-alias-markdown-placeholder': '#637094',
  '--dsw-alias-markdown-tag': '#e8edff',
  '--dsw-alias-scrollbar-bg-l1': 'rgba(49, 72, 145, 0.12)',
  '--dsw-alias-scrollbar-bg-l2': 'rgba(49, 72, 145, 0.18)',
  '--dsw-alias-scrollbar-hover-l1': 'rgba(49, 72, 145, 0.25)',
  '--dsw-alias-scrollbar-hover-l2': 'rgba(49, 72, 145, 0.32)',
  '--dsw-alias-state-business-primary': '#0e1adf',
  '--dsw-alias-state-business-tertiary': '#e8edff',
  '--dsw-alias-toast-bg': '#ffffff',
  '--dsw-alias-tooltip-bg': '#ffffff',
  '--dsw-specific-bubble': '#edf1ff',
  '--dsw-specific-bubble-highlight': '#e2e9ff',
  '--dsw-specific-input-major': '#ffffff',
  '--dsw-specific-login-input': '#ffffff',
  '--dsw-specific-menu': '#ffffff',
  '--dsw-specific-selector': '#ffffff',
  '--dsw-specific-sidebar-fill': '#f0f4ff',
  '--dsw-specific-sidebar-nav-item-active': '#e1e7ff',
  '--dsw-specific-sidebar-nav-item-active-accent': '#0e1adf',
  '--dsw-specific-sidebar-nav-item-hover': '#e7edff',
  '--dsw-specific-tip': '#edf1ff',
}

export const OCTACARBON_SKIN = Object.freeze({
  id: 'octacarbon', name: '能碳章鱼', builtin: true, version: '1.0.0',
  author: '能碳章鱼', description: '标识原色蓝 · 清透浅色界面 · 低对比度品牌底纹 · 能碳大脑欢迎页',
  colorScheme: 'light', tokens: OCTACARBON_TOKENS,
  css: readFileSync(new URL('../assets/octacarbon/theme.css', import.meta.url), 'utf8'),
  background: null,
})

// 固定资源清单，不把请求中的文件路径直接交给文件系统。
export const OCTACARBON_ASSETS = Object.freeze({
  'logo-en.png': 'image/png',
  'logo-zh.png': 'image/png',
  'logo-combined.png': 'image/png',
  'favicon.svg': 'image/svg+xml',
})
